"""Generate machine- and human-readable engagement reports."""

from __future__ import annotations

import json
import os
import time
from dataclasses import dataclass, field

from ..authorization import Engagement
from ..engine.models import Finding

_SEVERITY_ORDER = {"critical": 0, "high": 1, "medium": 2, "low": 3, "info": 4}


@dataclass
class Report:
    engagement: Engagement
    findings: list[Finding] = field(default_factory=list)
    targets_tested: int = 0
    requests_sent: int = 0
    started_at: float = field(default_factory=time.time)
    finished_at: float = 0.0
    ai_status: str = "disabled"
    ai_recommendation: str = ""

    def finalize(self) -> "Report":
        self.finished_at = time.time()
        self.findings.sort(key=lambda f: _SEVERITY_ORDER.get(f.severity.value, 9))
        return self

    # -- serialization ---------------------------------------------------
    def to_dict(self) -> dict:
        return {
            "tool": "VoidStrike",
            "project": "VoidSec-Hub / VoidStrike",
            "engagement": self.engagement.to_dict(),
            "summary": {
                "targets_tested": self.targets_tested,
                "requests_sent": self.requests_sent,
                "findings": len(self.findings),
                "by_severity": self._by_severity(),
                "duration_seconds": round((self.finished_at or time.time()) - self.started_at, 2),
                "ai_status": self.ai_status,
            },
            "findings": [f.to_dict() for f in self.findings],
            "ai_recommendation": self.ai_recommendation,
        }

    def _by_severity(self) -> dict:
        counts: dict[str, int] = {}
        for f in self.findings:
            counts[f.severity.value] = counts.get(f.severity.value, 0) + 1
        return counts

    def write_json(self, path: str) -> None:
        _ensure_dir(path)
        with open(path, "w", encoding="utf-8") as fh:
            json.dump(self.to_dict(), fh, indent=2)

    def write_markdown(self, path: str) -> None:
        _ensure_dir(path)
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(self.render_markdown())

    def render_markdown(self) -> str:
        e = self.engagement
        lines = [
            "# VoidStrike Assessment Report",
            "",
            "> Generated by VoidStrike (VoidSec-Hub). Only use this on authorized "
            "targets; unauthorized testing is illegal.",
            "",
            "## Engagement",
            "",
            f"- **Name:** {e.name}",
            f"- **Authorized by:** {e.authorized_by or 'n/a'}",
            f"- **Reference:** {e.reference or 'n/a'}",
            f"- **In scope:** {', '.join(e.in_scope) or 'n/a'}",
            "",
            "## Summary",
            "",
            f"- Targets tested: **{self.targets_tested}**",
            f"- Requests sent: **{self.requests_sent}**",
            f"- Findings: **{len(self.findings)}**",
            f"- By severity: {self._by_severity() or '{}'}",
            f"- AI assistance: {self.ai_status}",
            "",
        ]
        if self.ai_recommendation:
            lines += ["> **Suggested next step:** " + self.ai_recommendation, ""]

        if not self.findings:
            lines += ["## Findings", "", "_No remote-code-execution findings confirmed._", ""]
        else:
            lines += ["## Findings", ""]
            for i, f in enumerate(self.findings, 1):
                lines += [
                    f"### {i}. {f.vuln_class} — {f.severity.value.upper()} "
                    f"({f.confidence.value})",
                    "",
                    f"- **ID:** `{f.finding_id}`",
                    f"- **URL:** `{f.url}`",
                    f"- **Injection point:** `{f.injection_point}`",
                    f"- **Method:** {f.method}",
                    f"- **Oracle:** {f.oracle}",
                    f"- **Response status:** {f.response_status}",
                    "",
                    "**Proof-of-concept payload**",
                    "",
                    "```",
                    f.payload,
                    "```",
                    "",
                ]
                if f.evidence:
                    lines += ["**Evidence**", "", "```", f.evidence, "```", ""]
                if f.ai_signal:
                    lines += [f"_Signal: {f.ai_signal}_", ""]
                if f.remediation:
                    lines += ["**Remediation**", "", f.remediation, ""]
        lines += [
            "---",
            "",
            "_All testing was performed under the authorization described above. "
            "Any file artifacts (e.g. test upload shells) noted in the run log "
            "should be removed as part of engagement cleanup._",
        ]
        return "\n".join(lines)


def _ensure_dir(path: str) -> None:
    d = os.path.dirname(os.path.abspath(path))
    os.makedirs(d, exist_ok=True)
